apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy29
  labels:
    app: autodeploy29
  namespace: namespace-workflow-1714379612034
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy29
  template:
    metadata:
      labels:
        app: autodeploy29
    spec:
      containers:
        - name: autodeploy29
          image: acrworkflow1714379612034.azurecr.io/image-workflow-1714379612034:latest
          ports:
            - containerPort: 5000